name: publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Updated registry version'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository source
        uses: actions/checkout@v3

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: '19.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci
        
      - name: Install TypeScript
        run: npm install -g typescript

      - name: Compile TypeScript
        run: tsc

      - name: ESLint check
        run: npx eslint .

      - name: Update package version
        run: npm version ${{ github.event.inputs.version }} -m "Release ${{ github.event.inputs.version }} ✨"

      - name: Push changes
        run: git push --follow-tags

      - name: Publish to npm.js
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}